diagrama de componentes
@startuml

package "Sistema de Aluguel de Carros" {
    
    [Navegador] <.. [API]

    [API] -(0- [Gerenciador de Aluguéis]
    [API] -(0- [Gerenciador de Propostas]
    [API] -(0- [Gerenciador de Automóveis]

    [Gerenciador de Aluguéis] -(0- [PostgreSQL]:<<TCP/IP>>
    [Gerenciador de Propostas] -(0- [PostgreSQL]:<<TCP/IP>>
    [Gerenciador de Automóveis] -(0- [PostgreSQL]:<<TCP/IP>>

    [Cliente] <.. [Navegador]
    [Agente] <.. [Navegador]

}

@enduml
