@startuml Sistema de Aluguel de Carros

class Usuario{
    -nome: String
    -login: String
    -senha: String
    +gets(): String
    +sets(): void
}

class Cliente extends Usuario {
    -RG: String
    -CPF: String
    -endereco: String
    -profissao: String
    -empresa: String
    -salarios: String[3]
    +fazerPedido(): Pedido
    +consultarPedido(): Pedido
    +modificarPedido(): Pedido
    +cancelarPedido(): void
}

class Agente extends Usuario{
    +modificarPedido(pedido: Pedido): void
    +avaliarPedido(pedido: Pedido): bool
    +criarContrato(pedido: Pedido): Contrato
}

class Pedido {
    -id: int
    -data: Date
    -status: String
    -cliente: Cliente
    -automovel: Automovel
}

class Automovel {
    -matricula: String
    -ano: int
    -marca: String
    -modelo: String
    -placa: String
    -proprietario: Usuario
}

class Contrato {
    -id: int
    -tipo: String
    -agente: Agente
    -automovel: Automovel
    -pedido: Pedido
    +registrarAutomovel(): void
}

Cliente "1" -- "*" Pedido
Agente "1" -- "*" Pedido
Pedido "1" -- "1" Automovel
Contrato "1" -- "1" Pedido
Contrato "1" -- "1" Agente
Contrato "1" -- "1" Automovel

@enduml
