@startuml Sistema de Aluguel de Carros


rectangle "Sistema de Aluguéis" {
    
    actor Usuário
    
    package Usuarios {
        actor Cliente
        actor Agente
    }

    Usuário  <|-- Agente  
    Usuário  <|-- Cliente  

    usecase "Gerenciar Alugueis"   as UC2
    usecase "Editar aluguel"      as UC3
    usecase "Avaliar proposta"     as UC4
    usecase "Gerenciar Automóveis" as UC6

    Cliente --> UC2

    Agente --> UC3
    Agente --> UC4
    Agente --> UC6
}

@enduml
