@startuml Sistema de Aluguel de Carros

actor Cliente
actor Agente

usecase "Cadastro no Sistema" as UC1
usecase "Gerenciar Pedido de Aluguel" as UC2
usecase "Editar Pedido de Aluguel" as UC3
usecase "Avaliar Pedido de Aluguel" as UC4
usecase "Gerenciar Contrato" as UC5
usecase "Registrar Automóvel" as UC6

Cliente --> UC1
Cliente --> UC2

Agente --> UC1
Agente --> UC3
Agente --> UC4
Agente --> UC5

UC5 --> UC6 : "<<include>>"

@enduml
