@startuml
actor Cliente
actor Agente

usecase "Cadastro no Sistema" as UC1
usecase "Criar Pedido de Aluguel" as UC2
usecase "Modificar Pedido de Aluguel" as UC3
usecase "Consultar Pedido de Aluguel" as UC4
usecase "Cancelar Pedido de Aluguel" as UC5
usecase "Avaliar Pedido de Aluguel" as UC6
usecase "Executar Contrato" as UC7
usecase "Analisar Pedido Financeiramente" as UC8
usecase "Registrar Automóvel" as UC9
usecase "Gerenciar Contrato de Crédito" as UC10

Cliente --> UC1 : "Cadastro"
Cliente --> UC2 : "Criar Pedido"
Cliente --> UC3 : "Modificar Pedido"
Cliente --> UC4 : "Consultar Pedido"
Cliente --> UC5 : "Cancelar Pedido"

Agente --> UC6 : "Modificar Pedido"
Agente --> UC8 : "Analisar Pedido"
Agente --> UC7 : "Executar Contrato"
Agente --> UC9 : "Registrar Automóvel"
Agente --> UC10 : "Gerenciar Contrato de Crédito"

UC8 --> UC7 : "Aprovação do Pedido"

@enduml
